server:
  port: ${PORT:8080}

spring:
  application:
    name: ticker-analyzer
  profiles:
#    active: webhook

yahoo:
  finance:
    query1:
      url: https://query1.finance.yahoo.com

bot:
  userName: "TickerAnalyzerBot"
  token: "1841422646:AAFCsCISuUn-BSKYWe2wHzpGi66yeMXKszk"
  url: https://ticker-analyzer.herokuapp.com
  botPath: webhook