server:
  port: ${PORT:8080}

spring:
  application:
    name: ticker-analyzer
  profiles:
    active: local

etf:
  csv: /Users/sergei/asa/src/devtools4me/ticker-analyzer/bot-java/service/conf/all.csv

yahoo:
  finance:
    query1:
      url: https://query1.finance.yahoo.com

alpha:
  vantage:
    url: https://www.alphavantage.co
    token: ${AV_TOKEN}

bot:
  userName: "TickerAnalyzerBot"
  token: ${BOT_TOKEN}
  url: https://ticker-analyzer.herokuapp.com
  botPath: webhook