server:
  port: ${PORT:8080}

spring:
  application:
    name: ticker-analyzer
  profiles:
    active: webhook-bot

etf:
  csv: /apps/all.csv

yahoo:
  finance:
    query1:
      url: https://query1.finance.yahoo.com

bot:
  userName: "TickerAnalyzerBot"
  token: ${BOT_TOKEN}
  url: https://ticker-analyzer.herokuapp.com
  botPath: webhook