CREATE TABLE EVENTS
(
  ID SERIAL NOT NULL,
  CREATED_AT timestamp with time zone NOT NULL,
  AGGREGATE_ID VARCHAR(255) NOT NULL,
  AGGREGATE_TYPE VARCHAR(255) NOT NULL,
  VERSION INT NOT NULL,
  EVENT_TYPE VARCHAR(255) NOT NULL,
  EVENT_DATA jsonb NOT NULL,
  PRIMARY KEY (ID)
);

CREATE INDEX EVENTS_AGG_ID_IDX ON EVENTS(AGGREGATE_ID);
